### ISSUE TITLE
How to create a fragment graph by extending the parent Fragment's graph?

### ISSUE THREAD

**Issue by soapsign** [adennie/fb-android-dagger#17]
I have make a reusable widget fragment that can be add into a activity or a fragment, but I dont know how to correctly inject things into this class as the object graph might come from its parent fragment or hosting activity.

**Comment by adennie** [comment]
That's a good question; I haven't worked on projects with (potentially) nested Fragments before.  But however a nested Fragment gets a reference to its "container" (the InjectingActivity or the containing InjectingFragment), that reference could be cast to the Injector interface and you could access its graph via the Injector.getObjectGraph() method.  Or, you could just inject from that graph using the Injector.inject() method.
